### ISSUE TITLE
Some sites wont open sidebar

### ISSUE THREAD

**Issue by Amparose** [karlicoss/promnesia#330] opened 2022-06-25 17:12 UTC
Ok, only one so far but I'd assume it happens on others.

- Firefox 101.0.1
- Promnesia 1.1.2

This page: https://www.browserparrot.com/ won't open Promnesia despite the eye showing "5 visits and 2 contexts" when hovered.

**Comment by karlicoss** [comment] 2022-10-23 00:05
Hey, thanks for reporting. I just tried the same site and it works for me. I'm on firefox 106.0 though, but unlikely that it would matter really.
Is it still not working for you? Is it never working? E.g. if you refresh the page and try to open promnesia, still not working?

**Comment by karlicoss** [comment] 2022-12-31 00:53
closing since can't reproduce, but feel free to reopen if you manage

**Closed as completed by karlicoss** 2022-12-31 00:53 UTC

**Comment by krillin666** [comment] 2023-02-20 13:12
I can reproduce this in the website mentioned by OP and in other websites too

All I have in the console on this: `promnesia: bindSidebarData: 1 iterations passed, took 1676898780758  ms`
